# Generated by Django 5.2.1 on 2025-06-18 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
    ]
