# Generated by Django 5.2.1 on 2025-07-08 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_job_delete_clientcustomfieldvalue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='client',
        ),
    ]
