# Generated by Django 5.2.1 on 2025-07-08 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_remove_job_client'),
        ('invoices', '0002_invoice_paid_at_alter_invoice_job'),
        ('tasks', '0002_alter_task_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
