# Generated by Django 5.2.1 on 2025-07-08 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0004_remove_job_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='Job Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('CLOSED', 'Closed'), ('CANCELED', 'Canceled'), ('ON_HOLD', 'On Hold')], default='NEW', max_length=15)),
                ('schedule_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='customers.client')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='jobs_job_status_7d017a_idx'), models.Index(fields=['created_at'], name='jobs_job_created_1b3a4d_idx')],
            },
        ),
    ]
