# Generated by Django 5.2.1 on 2025-06-10 08:02

import customers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, help_text='Enter a 10-digit phone number without spaces or symbols.', max_length=10, null=True, validators=[customers.models.validate_phone_number])),
                ('address', models.TextField(blank=True, null=True)),
                ('password', models.CharField(help_text='Password will be stored in a hashed format.', max_length=128)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
